version: '3.9'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - new-network
    env_file:
      - .env

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
      - /app/node_modules  # Исключаем node_modules, чтобы не было конфликтов
    depends_on:
      - database
    networks:
      - new-network
    env_file:
      - .env

volumes:
  db-data: {}

networks:
  new-network:
    driver: bridge